language: python
python:
  - "3.4"
  - "3.5"
install:
  - pip install -q -r requirements.txt
  - pip install -q coveralls
script:
  - coverage run --source=objeros,crawler manage.py test
env:
  - DJANGO=1.9.7
  - DJANGO=1.10
after_success:
  coveralls
